create or replace function public.is_admin_user()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(coalesce(p.role, 'student')) in ('admin', 'super_admin', 'owner')
  );
$$;

create table if not exists public.admin_announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  message text not null,
  audience text not null default 'all',
  status text not null default 'published',
  expires_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_announcements_audience_check check (audience in ('all', 'students', 'admins')),
  constraint admin_announcements_status_check check (status in ('published', 'draft', 'archived'))
);

create table if not exists public.admin_activity_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_role text,
  action_type text not null,
  target_type text,
  target_id text,
  description text not null,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_admin_announcements_status
  on public.admin_announcements(status, created_at desc);

create index if not exists idx_admin_announcements_expires_at
  on public.admin_announcements(expires_at);

create index if not exists idx_admin_activity_logs_created_at
  on public.admin_activity_logs(created_at desc);

create index if not exists idx_admin_activity_logs_action_type
  on public.admin_activity_logs(action_type);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_admin_announcements_updated_at on public.admin_announcements;

create trigger set_admin_announcements_updated_at
before update on public.admin_announcements
for each row
execute function public.set_updated_at();

alter table public.admin_announcements enable row level security;
alter table public.admin_activity_logs enable row level security;

drop policy if exists "Admin announcements select published" on public.admin_announcements;
create policy "Admin announcements select published" on public.admin_announcements
for select
using (
  status = 'published'
  and (expires_at is null or expires_at > now())
);

drop policy if exists "Admin announcements admin select all" on public.admin_announcements;
create policy "Admin announcements admin select all" on public.admin_announcements
for select
using (public.is_admin_user());

drop policy if exists "Admin announcements admin manage" on public.admin_announcements;
create policy "Admin announcements admin manage" on public.admin_announcements
for all
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "Admin activity logs admin read" on public.admin_activity_logs;
create policy "Admin activity logs admin read" on public.admin_activity_logs
for select
using (public.is_admin_user());

drop policy if exists "Admin activity logs admin insert" on public.admin_activity_logs;
create policy "Admin activity logs admin insert" on public.admin_activity_logs
for insert
with check (public.is_admin_user());

drop policy if exists "Enrollments admin select" on public.enrollments;
create policy "Enrollments admin select" on public.enrollments
for select
using (public.is_admin_user());

drop policy if exists "Enrollments admin update" on public.enrollments;
create policy "Enrollments admin update" on public.enrollments
for update
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "Enrollment receipts admin read" on storage.objects;
create policy "Enrollment receipts admin read" on storage.objects
for select
using (
  bucket_id = 'enrollment-receipts'
  and public.is_admin_user()
);

drop policy if exists "Course ratings admin moderate update" on public.course_ratings;
create policy "Course ratings admin moderate update" on public.course_ratings
for update
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "Course ratings admin moderate delete" on public.course_ratings;
create policy "Course ratings admin moderate delete" on public.course_ratings
for delete
using (public.is_admin_user());

drop policy if exists "Profiles admin read all" on public.profiles;
create policy "Profiles admin read all" on public.profiles
for select
using (public.is_admin_user());

drop policy if exists "Profiles admin update all" on public.profiles;
create policy "Profiles admin update all" on public.profiles
for update
using (public.is_admin_user())
with check (public.is_admin_user());
